#server:
#  port: ${SERVER_PORT:8080}
#
#spring:
#  datasource:
#    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:4999}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    generate-ddl: true
#    database-platform:
#      org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kun_uz
    username: postgres
    password: 4999
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database-platform:
      org.hibernate.dialect.PostgreSQLDialect

jwt:
  access:
    token:
      expiry: 3600000 # 60 minutes
      secret:
        key: 8d1877ec5cb495b9cd9993c636a54ee0e7486212232baaa269dd731bb1ccb6ee

  refresh:
    token:
      expiry: 864000000 # 10 days
      secret:
        key:
